[project]
name = "numba-experiments"
version = "0.1.0"
description = "Add a short description here"
authors = ["Aditya Goel <agoel4512@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = ">=3.12.3,<3.13"
numba = ">=0.59.1,<0.60"

[feature.test.dependencies]
pytest = ">=7.2.0,<7.3"
